config/routes.rb
Rails.application.routes.draw do
 devise_for :users

  root 'notes#index'
  get 'notes/index'
  get 'users/profile'
  post 'notes/new'



  resources :users
  resources :tasks
  resources :notes
  namespace :notes do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  def enbedable_url
    youtube_id = description.split("?v=").last
    "https://www.youtube.com/embed/#{youtube_id}"
  end

end

app/models/profile_picture.rb
class Profilepicture < ApplicationRecord
  belongs_to :user 

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :notes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token
  # GET /notes or /notes.json
  def index
    @notes = current_user.notes.order(cached_votes_score: :desc)
    if nil
    end
  
  end
  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note

      @note = current_user.notes.find(params[:id])

    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_notes
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET notes/1/tasks
  def index
    @tasks = @notes.tasks
  end

  # GET notes/1/tasks/1
  def show
  end

  # GET notes/1/tasks/new
  def new
    @task = @notes.tasks.build
  end

  # GET notes/1/tasks/1/edit
  def edit
  end

  # POST notes/1/tasks
  def create
    @task = @notes.tasks.build(task_params)

    if @task.save
      redirect_to([@task.notes, @task], notice: 'Task was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT notes/1/tasks/1
  def update
    if @task.update_attributes(task_params)
      redirect_to([@task.notes, @task], notice: 'Task was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE notes/1/tasks/1
  def destroy
    @task.destroy

    redirect_to notes_tasks_url(@notes)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notes
      @notes = current_user.notes.find(params[:notes_id])
    end

    def set_task
      @task = @notes.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description, :status, :notes_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @user_notes = @user.notes
    @user_profile = @user.profile
    @user_profile_picture = @user.picture
  end

  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
   end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Like A Forest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="background">

    <%= render 'notes/navbar' %>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<main>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :"Put youtube URL here > " %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit :"Create Video Link Now "%>
  </div>
</main>
<% end %>

app/views/notes/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Like A Forest</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Add', new_note_path, method: :note, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Profile', users_profile_url, class: 'nav-link'%>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link'%>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/notes/edit.html.erb
<div class="h1">
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>
</div>

app/views/notes/index.html.erb
<!DOCTYPE html>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">


<h2> listen to chilledcow </h2>

<div>
<iframe class="main" height="320px" width="100%" src="https://www.youtube.com/embed/DWcJFNfaw9c?autoplay=1"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"> </iframe>
</div>

      <p> YOUTUBE LIKE A FOREST </p>
      <th colspan="3"></th>

    <% @notes.each do |note| %>
        <!--<td><%= note.name %></td> -->
    <div>
      <p style="text-align: center;"><iframe  height="" width="" src="<%= note.enbedable_url %>" frameborder="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"> </iframe></p>
     <tr>

      <td><%= link_to 'Show', note %></td>
      <td><%= link_to 'Edit', edit_note_path(note) %></td>
      <td><%= link_to 'Delete', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'Add', new_note_path %></td>
      <br> </br>
      </tr>
    </div>
    <% end %>

<div>
    <footer>
      Copyright 42069 all rights reserved

    </footer>
  </div>

app/views/notes/new.html.erb
<div class="h1">
<h1>New Video</h1>


<%= render 'form', note: @note  %>

<%= link_to 'Back', notes_path %>
</div>

app/views/notes/show.html.erb
<div class="content2">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @note.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @note.description %>
</p>
<iframe autoplay height="500px" width="100%" src="<%= @note.enbedable_url %>" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"> </iframe>

<p>
  <strong>User:</strong>
  <%= @note.user_id %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>
</div>


<%# show.html.erb -> /notes/1 %>

app/views/tasks/_form.html.erb
<%= form_with(model: [@task.notes, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', [@task.notes, @task] %> |
<%= link_to 'Back', notes_tasks_path(@task.notes) %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= task.notes %></td>
    <td><%= link_to 'Show', [task.notes, task] %></td>
    <td><%= link_to 'Edit', edit_notes_task_path(task.notes, task) %></td>
    <td><%= link_to 'Destroy', [task.notes, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_notes_task_path(params[:notes_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_tasks_path(@task.notes) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Notes:</b>
  <%= @task.notes %>
</p>


<%= link_to 'Edit', edit_notes_task_path(@task.notes, @task) %> |
<%= link_to 'Back', notes_tasks_path(@task.notes) %>

app/views/users/_user.html.erb
  <% puts '@user' %>

app/views/users/picture.html.erb
<%= render 'users/user' %>

app/views/users/profile.html.erb
<h> url go here </h>

<h1 class="featured">this page is under development and should be here soon</h1>



<p>This is your page</p>

<div>
<img src="http://images4.fanpop.com/image/photos/16100000/Cute-Kitten-kittens-16123546-1280-800.jpg" alt="Flowers in China">
</div>

<p> Hope you like cats</p>